---
# tasks file for zendserver

- apt_key: url=http://repos.zend.com/zend.key state=present

- include: main-debian-7.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'

- apt: name=zend-server-php-5.6 state=present update_cache=yes
  notify: restart-zend-server

#- apt: name=zend-server-nginx-php-5.6 state=present

- include: mysql-benchmark-tools.yml
  when: mysql_benchmark_install == true

